FROM quay.io/caracan/apd-base:latest@sha256:5e3244165189346240f818507dc56db278fe23545d96ecf8246f36d7d6727f6f

RUN dnf -y install qemu-guest-agent; \
	dnf clean all; \
    systemctl enable qemu-guest-agent; \
    rm /var/{log,cache,lib}/* -rf 