FROM quay.io/caracan/apd-base:latest@sha256:f5e4dbd8e2e14fff7c37278e75e51cc7e641e7e3349fca3deaf74ef4cc6ab678

RUN dnf -y install qemu-guest-agent podman-compose; \
	dnf clean all; \
    systemctl enable qemu-guest-agent; \
    rm /var/{log,cache,lib}/* -rf 