FROM quay.io/caracan/apd-base:latest@sha256:2bda9b57ab9d0fdd7b545ecdfd1a94401e939b5dbf424d371e3411dbb16b495c

RUN dnf -y install qemu-guest-agent podman-compose; \
	dnf clean all; \
    systemctl enable qemu-guest-agent; \
    rm /var/{log,cache,lib}/* -rf 
