FROM quay.io/caracan/apd-base:latest@sha256:47850cfe5652a37642c51866f395cb1b5e643be513c2859ada4b683ea73f5ead

RUN echo "qemu:x:107:107:qemu user:/:/sbin/nologin" >> /etc/passwd && \
      dnf -y install qemu-kvm libvirt virt-install virt-viewer cockpit-machines && \
      systemctl enable libvirt-guests && \
      dnf clean all; \
      rm -rf /var/log/dnf5.log* /var/lib/dnf/ /var/cache/ibdnf5/;
	  
RUN bootc container lint
