FROM quay.io/caracan/apd-base:latest@sha256:acbf059c6959e823d87c672c27ca28863458023df38108efb95f472062b7035c

RUN echo "qemu:x:107:107:qemu user:/:/sbin/nologin" >> /etc/passwd && \
      dnf -y install qemu-kvm libvirt virt-install virt-viewer cockpit-machines && \
      systemctl enable libvirt-guests && \
      dnf clean all; \
      rm -rf /var/log/dnf5.log* /var/lib/dnf/ /var/cache/ibdnf5/;
	  
RUN bootc container lint