FROM quay.io/caracan/apd-base:latest@sha256:73118413ac244454f9c2930df0c2992194f494938e365c98620423be30df60c5

RUN echo "qemu:x:107:107:qemu user:/:/sbin/nologin" >> /etc/passwd && \
      dnf -y install qemu-kvm libvirt virt-install virt-viewer cockpit-machines && \
      systemctl enable libvirt-guests && \
      dnf clean all; \
      rm -rf /var/log/dnf5.log* /var/lib/dnf/ /var/cache/ibdnf5/;
	  
RUN bootc container lint