
FROM quay.io/fedora/fedora-bootc:43@sha256:0c2fc49356baa00cba282610e66ebcf0bb22364ffc86a9d1a6cca1434a31b00d

RUN dnf -y install NetworkManager openssh-server sudo firewalld podman cockpit cockpit-podman acl systemd-container nfs-utils wget bash-color-prompt; \
	dnf clean all; \
	systemctl enable cockpit.socket; \
        firewall-offline-cmd --add-service cockpit; \
        rm /var/{log,cache,lib}/* -rf

COPY wheel-nopasswd /etc/sudoers.d