
FROM quay.io/fedora/fedora-bootc:43@sha256:1cfbf52f3fc967a6047a38e6fa81c5779439c4d821a5ff0f3265c53662886958

RUN dnf -y install NetworkManager openssh-server sudo firewalld podman cockpit cockpit-podman acl systemd-container nfs-utils wget; \
	dnf clean all; \
	systemctl enable cockpit.socket; \
        firewall-offline-cmd --add-service cockpit; \
        rm /var/{log,cache,lib}/* -rf

COPY wheel-nopasswd /etc/sudoers.d