
FROM quay.io/fedora/fedora-bootc:43@sha256:435ffdc2bb1fdef330839024f4ed6b277b8d68de7131c4addd18d9bea1d2b374

RUN dnf -y install NetworkManager openssh-server sudo firewalld podman cockpit cockpit-podman acl systemd-container nfs-utils wget bash-color-prompt; \
	dnf clean all; \
	systemctl enable cockpit.socket; \
        firewall-offline-cmd --add-service cockpit; \
        rm /var/{log,cache,lib}/* -rf

COPY wheel-nopasswd /etc/sudoers.d